default:
  tags:
    - linux-k8s
  image:
    name: hugomods/hugo:0.129.0
    entrypoint: ["/bin/sh", "-c"]
  before_script:
    - apk update && apk upgrade && apk add --no-cache nodejs npm bash curl perl git openssh-client

stages:
  - test-translation
  - push-to-github
variables:
  TERM: "xterm"
  NUKE_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master"

test:
  stage: test-translation
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /^Gai18n:.*\/Ready for testing$/'
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.saltov.dynabic.com/spb/webapps/utilities/docs-content-tester.git
    - chmod u+x docs-content-tester/build.sh
    - cd docs-content-tester && ./build.sh Build

push-to-github:
  stage: push-to-github
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$GITHUB_DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git checkout master
    - git remote add github git@github.com:aspose-email/Aspose.Email-Documentation.git
    - git push github master
