default:
  tags:
    - linux-k8s
  image:
    name: hugomods/hugo:0.129.0
    entrypoint: ["/bin/sh", "-c"]
  before_script:
    - apk update && apk upgrade && apk add --no-cache nodejs npm bash curl perl git
    - "git config --global http.extraheader 'Authorization: Bearer $GITLAB_ACCESS_TOKEN'"
    - git clone https://git.saltov.dynabic.com/spb/webapps/utilities/docs-content-tester.git

stages:
  - test-translation
variables:
  TERM: "xterm"
  NUKE_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

clone_repo:
  stage: test-translation
  script:
    - ls -la
  when: manual
