default:
  tags:
    - linux-k8s
  image:
    name: hugomods/hugo:0.129.0
    entrypoint: ["/bin/sh", "-c"]
  before_script:
    - apk update && apk upgrade && apk add --no-cache nodejs npm bash curl perl git

stages:
  - test-translation
variables:
  TERM: "xterm"
  NUKE_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

test:
  stage: test-translation
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /^Gai18n:.*\/Ready for testing$/'
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.saltov.dynabic.com/spb/webapps/utilities/docs-content-tester.git
    - chmod u+x docs-content-tester/build.sh
    - cd docs-content-tester && ./build.sh Build
